extends: "stylelint-config-standard-scss"
rules:
  block-opening-brace-space-before: null
  color-hex-length: long
  custom-property-empty-line-before: null
  declaration-block-single-line-max-declarations: null
  declaration-colon-space-after: null
  declaration-empty-line-before: null
  font-family-name-quotes: always-unless-keyword
  no-descending-specificity: null
  selector-descendant-combinator-no-non-space: null
  selector-list-comma-newline-after: null
  selector-class-pattern: "[a-z_-]+"
  selector-id-pattern: "[a-z_-]+"
  scss/dollar-variable-pattern: "[a-z_-]+"
  scss/operator-no-unspaced: null
  scss/comment-no-empty: null
  shorthand-property-no-redundant-values: null
