extends: "stylelint-config-standard"
rules:
  at-rule-no-unknown: [true, ignoreAtRules: [extend, include, mixin]]
  block-opening-brace-space-before: null
  declaration-block-single-line-max-declarations: null
  declaration-empty-line-before: null
  no-descending-specificity: null
  selector-descendant-combinator-no-non-space: null
  selector-list-comma-newline-after: null
