# A Docker Compose file that launches a minimal Danbooru instance. This is
# suitable as a quick demo or for personal use, not for public-facing sites.
#
# Usage:
#
#     $ docker-compose -f config/docker/docker-compose.simple.yaml up
#     $ docker-compose -f config/docker/docker-compose.simple.yaml down

version: "3.7"
services:
  danbooru:
    # image: evazion/danbooru
    build:
      context: ../..
      dockerfile: config/docker/Dockerfile.danbooru
    ports:
      - "80:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://danbooru@postgres/danbooru
      - DANBOORU_CANONICAL_URL=http://localhost
    volumes:
      - "danbooru-images:/home/danbooru/app/public/data"
    depends_on:
      - postgres
    entrypoint: ["bash", "-c", "bin/rails db:setup 2> /dev/null; bin/rails server -b 0.0.0.0"]
    user: root

  postgres:
    # image: evazion/postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: danbooru
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "danbooru-data:/var/lib/postgresql/data"

volumes:
  danbooru-images:
    name: danbooru-images
  danbooru-data:
    name: danbooru-data
